cmake_minimum_required(VERSION 4.1)
project(projet_algo_s2)

set(CMAKE_CXX_STANDARD 14)

add_executable(projet_algo_s2
        .idea/.gitignore
        .idea/modules.xml
        .idea/projet-algo-s2.iml
        .idea/vcs.xml
        .idea/workspace.xml
        .gitignore
        README.md
        src/main.c)
